config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :publications, only: [:index, :show]
  namespace :admin do
    resources :publications 
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/publication.rb
class Publication < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < AdminController
    before_action :find_publication, only: [:show, :edit, :update, :destroy]

    def index 
        @publications = Publication.all 
    end

    def show; end

    def new 
        @publication = Publication.new 
    end

    def create 
        @publication = Publication.new(publication_params)
        if @publication.save 
            redirect_to admin_publication_path(@publication)
        else 
            render :new, alert: 'something went wrong'
        end
    end

    def edit;end 

    def update 
        if @publication.update(publication_params)
            redirect_to admin_publication_path(@publication)
        else 
            render :edit, alert: 'something went wrong'
        end
    end

    def destroy 
        @publication.destroy 
        redirect_to admin_publication_path, alert: 'successfully deleted publication'
    end
    
    private 

    def find_publication 
        @publication = Publication.find(params[:id])
    end

    def publication_params 
        params.require(:publication).permit(:title, :description, :file_url)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    before_action :check_for_admin 
    def check_for_admin 
        if current_user.nil? || !current_user.is_admin?
            redirect_to root_path, alert: "you must be an admin to access this path"
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController 
    def index 
        @publications = Publication.all 
    end 
    
    def show 
        @publication = Publication.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/new.html.erb
<h3> New publication  </h3>

<%= form_for @publication, url: admin_publications_path do |f| %>
    <div class='form-group'>
        <label> title </label>
        <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class='form-group'>
        <label> Description </label>
        <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class='form-group'>
        <label> file URL </label>
        <%= f.text_field :file_url, class: 'form-control'%>
    </div>
    <div class='form-group'>
        <%= f.submit "Post new publication", class: 'btn btn-primary'%>
    </div>
<%end%>

app/views/admin/publications/index.html.erb
<h2> publications </h2>

<div>
    <%= link_to 'new publication',  new_admin_publication_path, class: 'btn btn-primary'%>
</div> 

<% @publications.each do |publication| %>
    <div class='panel panel-default'>
        <div class= 'panel-heading'>
            <h3 class='panel-title'> <%= publication.title %></h3>
        </div>
        <div class='panel-body'>
          <p><%= publication.description %> </p>
          <p><%= publication.file_url %> </p>
        </div>
        <div class='panel-footer'>
            <%= link_to 'view more detail', admin_publication_path(publication), class: 'btn btn-default'%>
            <%= link_to 'edit', edit_admin_publication_path(publication), class: 'btn btn-default'%>
        </div>
    </div>
<%end%>

app/views/admin/publications/show.html.erb
<div class='panel panel-default'>
    <div class='panel-heading'>
        <h3 class='panel-title'> <%= @publication.title%> </h3>
    </div>
    <div class='panel-body'>
        <p> <%= @publication.description %> </p>
        <p> <%= @publication.file_url %> </p>
    </div>
</div>
 

app/views/application/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">SubscriptionApp</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
           <% if user_signed_in?%>
            <li>
                <a class= "nav-link"> <%= link_to "Sign out", destroy_user_session_path, method: :delete %> 
            </li>  
            <li>
                <a class= "nav-link"> Signed in as <%= current_user.email%> <span class="sr-only">(current)</span></a>
            </li>
        <%else%> 
            <li class="nav-item">
                <a class= "nav-link"> <%= link_to "Sign in", new_user_session_path %>  <span class="sr-only">(current)</span></a>
            </li> 
            
            <li class="nav-item">
                <a class="nav-link"> <%= link_to "Sign up", new_user_registration_path %>  <span class="sr-only">(current)</span></a>
            </li>   
        <%end%>
        
    </ul>
    
  </div>
</nav>

app/views/home/index.html.erb
<h1> hola mundo  </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SubscriptionApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "nav" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>


    <%= yield %>
  </body>
</html>

app/views/publications/index.html.erb
<h2> publications </h2>

<% @publications.each do |publication| %>
    <div class='panel panel-default'>
        <div class= 'panel-heading'>
            <h3 class='panel-title'> <%= publication.title %></h3>
        </div>
        <div class='panel-body'>
          <p><%= publication.description %> </p>
          <p><%= publication.file_url %> </p>
        </div>
        <div class='panel-footer'>
            <%= link_to 'view more detail', publication_path(publication), class: 'btn btn-default'%>
        </div>
    </div>
<%end%>